---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/
# and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
ENABLE_LINTERS: # All other linters will be disabled by default
  - ACTION_ACTIONLINT
  - API_SPECTRAL
  - ARM_ARM_TTK
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - BICEP_BICEP_LINTER
  - C_CLANG_FORMAT
  - C_CPPCHECK
  - C_CPPLINT
  - CLOUDFORMATION_CFN_LINT
  - COPYPASTE_JSCPD
  - CPP_CLANG_FORMAT
  - CPP_CPPCHECK
  - CPP_CPPLINT
  - CREDENTIALS_SECRETLINT
  - CSS_SCSSLINT
  - CSS_STYLELINT
  - DOCKERFILE_DOCKERFILELINT
  - DOCKERFILE_HADOLINT
  - ENV_DOTENV_LINTER
  - GHERKIN_GHERKIN_LINT
  - GIT_GIT_DIFF
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_DJLINT
  - HTML_HTMLHINT
  - JAVASCRIPT_ES
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_JSONLINT
  - JSON_NPM_PACKAGE_JSON_LINT
  - JSON_PRETTIER
  - JSON_V8R
  - KOTLIN_DETEKT
  - KOTLIN_KTLINT
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - OPENAPI_SPECTRAL
  - PROTOBUF_PROTOLINT
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - R_LINTR
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GOODCHECK
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_LS_LINT
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRUFFLEHOG
  - SPELL_LYCHEE
  - SPELL_MISSPELL
  - SPELL_PROSELINT
  - SPELL_VALE
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  - SWIFT_SWIFTLINT
  - TERRAFORM_CHECKOV
  - TERRAFORM_KICS
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT

SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect
# errors but not block CI to pass
